[rocm-libraries] ROCm/rocm-libraries#3906 (commit ec2e9a7)
rocRoller: KernelGraphTest.Transformer: use
 Expression::identical (#3906)

Use `Expression::identical` instead of `operator==` in
`KernelGraphTest.Transformer` to verify the resulting transformers are
really identical

* `ExpressionPtr`'s `operator==` returns an `ExpressionPtr` for
expression-building
* The returned `ExpressionPtr` represents the expression and not the
result of the comparison
* This patch changes the test to use `Expression::identical` to verify
      expression output is as expected

This also fixes the test failing to build on gcc 15 due to
boolean_testable concept checks in std::pair

CC: @amd-chunxlin

## Technial Details

KernelGraphTest.Transformer contains this snippet:

```
// The resulting transformers should be identical
for(auto op : kgraph1.control.getNodes())
  EXPECT_EQ(transformers.at(op).getIndexes(), kgraph1.buildTransformer(op).getIndexes());
```

`getIndexes()` returns `std::map<int, Expression::ExpressionPtr>`, so
`EXPECT_EQ` instantiates `std::map::operator==`, and `std::pair<const
int, Expression::ExpressionPtr>` equality comparison templates.

That code happens to build on gcc versions before 15, where `stl_pair.h`
from GNU libstdc++ contains code like:

```
  /// Two pairs of the same type are equal iff their members are equal.
  template<typename _T1, typename _T2>
    inline _GLIBCXX_CONSTEXPR bool
    operator==(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
    { return __x.first == __y.first && __x.second == __y.second; }
```

The `__x.second == __y.second` part would use the `operator==` that
returns an `ExpressionPtr` which is convertible to `bool`.

With g++ and libstdc++ newer than 15, `stl_pair.h` now contains:

```
  /// Two pairs are equal iff their members are equal.
  template<typename _T1, typename _T2, typename _U1, typename _U2>
    [[nodiscard]]
    constexpr bool
    operator==(const pair<_T1, _T2>& __x, const pair<_U1, _U2>& __y)
    requires requires {
      { __x.first == __y.first } -> __detail::__boolean_testable;
      { __x.second == __y.second } -> __detail::__boolean_testable;
    }
    { return __x.first == __y.first && __x.second == __y.second; }
```

The `{ __x.second == __y.second } -> __detail::__boolean_testable` check
would catch that the `ExpressionPtr` returned by `operator==` is not
convertible to `bool` and trigger a build time error like:

```
/include/c++/15/bits/stl_algobase.h:1191:22: error: invalid operands to binary expression ('const std::pair<const int, std::shared_ptr<std::variant<rocRoller::Expression::Add, rocRoller::Expression::Subtract, ... std::shared_ptr<rocRoller::KernelGraph::CoordinateGraph::WaveTile>>>>')
6.3      1191 |             if (!(*__first1 == *__first2))

   ( ... snipped ... )

6.3     /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/stl_pair.h:1034:39: note: because 'ExpressionPtr' (aka 'std::shared_ptr<std::variant<Add, Subtract, ...>>>') does not satisfy '__boolean_testable'
6.3      1034 |       { __x.second == __y.second } -> __detail::__boolean_testable;
```

This PR changes the unit test to use `ExpressionPtr::identical` from
`operator==`

This PR does not use `ExpressionPtr::equivalent` as it assumes the
relaxed commutativity/associativity algebraic properties of equivalent
expressions would not need to be considered when testing the output of
`buildTransformer`.

## Test Results

I've verified that `KernelGraphTest.Transfomer` still succeeds after
this change.

```
rocroller-tests --gtest_filter=KernelGraphTest.Transformer
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from KernelGraphTest
[ RUN      ] KernelGraphTest.Transformer
[       OK ] KernelGraphTest.Transformer (3 ms)
[----------] 1 test from KernelGraphTest (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3 ms total)
[  PASSED  ] 1 test.
```

Co-authored-by: Matthew Emmett <matthew.emmett@amd.com>